server:
  port: 8123
  servlet:
    context-path: /api
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000

spring:

  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB





mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # only print log in dev
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis configuration
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


# interface documentation
knife4j:
  enable: true
  openapi:
    title: Interface Documentation
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.eric.ekcloudgallerybackend.controller